Direct output to `frontend/bingo`

diff --git a/.github/workflows/zoomhub.yml b/.github/workflows/zoomhub.yml
--- a/.github/workflows/zoomhub.yml
+++ b/.github/workflows/zoomhub.yml
@@ -213,8 +213,8 @@ jobs:
 
           echo "Build exit code: $?"
 
-          echo "Checking if frontend/build exists:"
-          ls -la frontend/build/ || echo "frontend/build/ directory not found"
+          echo "Checking if frontend/bingo exists:"
+          ls -laR frontend/bingo || echo "frontend/bingo directory not found"
 
           echo '=========================================================='
           echo 'PRE: Haskell file deletion'
@@ -224,7 +224,7 @@ jobs:
           # NOTE: Delete Haskell source code. This directory is only mounted in
           # Snowpack configuration to enable Tailwind CSS ’purge’ feature. These
           # files are not meant to be shipped to the public website.
-          rm -rf frontend/build/__DELETE_ME__
+          rm -rf frontend/bingo/__DELETE_ME__
 
           echo '=========================================================='
           echo 'POST: Haskell file deletion'
@@ -310,7 +310,7 @@ jobs:
             workspace
 
       - name: Copy public files to workspace
-        run: cp --recursive frontend/build workspace/public
+        run: cp --recursive frontend/bingo workspace/public
 
       - name: Copy binaries workspace
         run: cp bin/* workspace
